package collegemanagment;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 * Servlet implementation class teacherdashboard
 */
@WebServlet("/teacherdashboard")
public class teacherdashboard extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public teacherdashboard() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		System.out.println("GET");
		try {
			HttpSession session=request.getSession(false);
			String a=(String)session.getAttribute("sid");
			
			Class.forName("com.mysql.cj.jdbc.Driver");
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/college","root","root");
			
			String sql = "SELECT * FROM details WHERE id='"+a+"'";
            PreparedStatement stmt=con.prepareStatement(sql);
			
            ResultSet rs=stmt.executeQuery();
        	while(rs.next()) {
//        		String firstname=request.getParameter("firstname");
//        		String lastname=request.getParameter("lastname");
//        		String email=request.getParameter("email");
//        		String phone=request.getParameter("phone");
//        		String branch=request.getParameter("branch");
//        		String employerid=request.getParameter("empid");
//        		String username=request.getParameter("username");
        		
    			System.out.println(rs.getString("id"));
    			System.out.println(rs.getString("firstname"));
    			System.out.println(rs.getString("lastname"));
    			System.out.println(rs.getString("email"));
    			System.out.println(rs.getString("phone"));
    			System.out.println(rs.getString("branch"));
    			System.out.println(rs.getString("empid"));
    		   
    			
    			

    		
    		System.out.println();
    		
        	PrintWriter p=response.getWriter();
        	p.print("<!DOCTYPE html>\r\n"
        			+ "<html lang=\"en\">\r\n"
        			+ "<head>\r\n"
        			+ "    <script src=\"https://kit.fontawesome.com/e674bba739.js\" crossorigin=\"anonymous\"></script>\r\n"
        			+ "\r\n"
        			+ "    <link rel=\"stylesheet\" href=\"dbt.css\">\r\n"
        			+ "    <meta charset=\"UTF-8\">\r\n"
        			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
        			+ "    <title>teacher's Dash-Board</title>\r\n"
        			+ "    <style>\r\n"
        			+ "*\r\n"
        			+ "{\r\n"
        			+ "margin: 0;\r\n"
        			+ "padding: 0;\r\n"
        			+ "}\r\n"
        			+ "body{\r\n"
        			+ "    background-image: url(images/mit.jpg);\r\n"
        			+ "    \r\n"
        			+ "    background-size: cover;\r\n"
        			+ "    background-repeat:no-repeat;\r\n"
        			+ "    display: flex;\r\n"
        			+ "    justify-content: center;\r\n"
        			+ "   \r\n"
        			+ "}\r\n"
        			+ ".frame{\r\n"
        			+ "    width: 1650px;\r\n"
        			+ "    height: 850px;\r\n"
        			+ "    background-color: rgba(0, 0, 0, 0.932);\r\n"
        			+ "   justify-content: center;\r\n"
        			+ "    margin-top: 35px;\r\n"
        			+ "\r\n"
        			+ "    \r\n"
        			+ "}\r\n"
        			+ "\r\n"
        			+ ".leftframe{\r\n"
        			+ "    \r\n"
        			+ "    margin-left: 30px;\r\n"
        			+ "    margin-top: 20px;\r\n"
        			+ "    height: 850px;\r\n"
        			+ "    width: 330px;\r\n"
        			+ "    background-color:  rgba(32, 31, 31, 0.774);\r\n"
        			+ "    box-shadow:  5px  rgb(0, 0, 0) ;\r\n"
        			+ "}\r\n"
        			+ ".profile\r\n"
        			+ "{\r\n"
        			+ "   \r\n"
        			+ "    height: 70px;\r\n"
        			+ "    width: 330px;\r\n"
        			+ "    background-color: rgba(7, 7, 7, 0);\r\n"
        			+ "  \r\n"
        			+ "}\r\n"
        			+ ".profile1\r\n"
        			+ "{\r\n"
        			+ " \r\n"
        			+ "    height: 70px;\r\n"
        			+ "    width: 330px;\r\n"
        			+ "    background-color: rgb(0, 0, 0);\r\n"
        			+ "    \r\n"
        			+ "    \r\n"
        			+ "}\r\n"
        			+ ".profile:hover\r\n"
        			+ "{\r\n"
        			+ "    \r\n"
        			+ "    height: 70px;\r\n"
        			+ "    width: 330px;\r\n"
        			+ "    background-color: rgb(0, 0, 0);\r\n"
        			+ "  \r\n"
        			+ "}\r\n"
        			+ "\r\n"
        			+ ".a{\r\n"
        			+ "   \r\n"
        			+ "    margin-left: 80px;\r\n"
        			+ "    padding-top: 25px;\r\n"
        			+ "    font-size: 17px;\r\n"
        			+ "    font-family: Arial, Helvetica, sans-serif;\r\n"
        			+ "   \r\n"
        			+ "}\r\n"
        			+ ".a a{\r\n"
        			+ "    color: rgb(173, 170, 170);\r\n"
        			+ "    text-decoration: none;\r\n"
        			+ "}\r\n"
        			+ ".topright{\r\n"
        			+ "    width: 1185px;\r\n"
        			+ "    height: 250px;\r\n"
        			+ "    background-color:  rgb(25, 25, 25);\r\n"
        			+ "    margin-top: -820px;\r\n"
        			+ "    margin-left: 410px;\r\n"
        			+ "    box-shadow: 9px 12px 5px rgba(0, 0, 0, 0.74) ;\r\n"
        			+ "    border-radius: 40px;\r\n"
        			+ "\r\n"
        			+ "}\r\n"
        			+ ".book{\r\n"
        			+ "    height: 250px;\r\n"
        			+ "    opacity: 1;\r\n"
        			+ "    margin-top: 0px;\r\n"
        			+ "    margin-left: 0px;\r\n"
        			+ "}\r\n"
        			+ ".dash{\r\n"
        			+ "    font-size: 25px;\r\n"
        			+ "    color: rgba(102, 100, 104, 0.664);\r\n"
        			+ "    margin-left: 230px;\r\n"
        			+ "    margin-top: 2px;\r\n"
        			+ "    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;\r\n"
        			+ "}\r\n"
        			+ ".welcome{\r\n"
        			+ "    font-size: 33px;\r\n"
        			+ "    color: rgba(102, 100, 104, 0.664);;\r\n"
        			+ "    margin-left: 910px;\r\n"
        			+ "    margin-top: -110px;\r\n"
        			+ "    font-family: Arial, Helvetica, sans-serif;\r\n"
        			+ "}\r\n"
        			+ ".mitheading{\r\n"
        			+ "    margin-top: -190px;\r\n"
        			+ "    margin-left: 230px;\r\n"
        			+ "    font-size: 27px;\r\n"
        			+ "    color: rgba(255, 255, 255, 0.664);\r\n"
        			+ "}\r\n"
        			+ ".name2{\r\n"
        			+ "    \r\n"
        			+ "    margin-left: 500px;\r\n"
        			+ "    width: 600px;\r\n"
        			+ "    height: 60px;\r\n"
        			+ "    font-size: 50px;\r\n"
        			+ "   margin-top: 5px;\r\n"
        			+ "    background-color: transparent;\r\n"
        			+ "    color: aqua;\r\n"
        			+ "    outline: 0;\r\n"
        			+ "    border: none;\r\n"
        			+ "}\r\n"
        			+ ".leftbottom{\r\n"
        			+ "    height: 509px;\r\n"
        			+ "    width: 770px;\r\n"
        			+ "    \r\n"
        			+ "    margin-top: 34px;\r\n"
        			+ "    margin-left: 410px;\r\n"
        			+ "    box-shadow: 9px 12px 5px rgba(0, 0, 0, 0.74) ;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "    background-color: rgb(25, 25, 25);\r\n"
        			+ "\r\n"
        			+ "}\r\n"
        			+ ".rightmiddle{\r\n"
        			+ "    height: 350px;\r\n"
        			+ "    width: 365px;\r\n"
        			+ "    box-shadow: 9px 12px 5px rgba(0, 0, 0, 0.74) ;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "    background-color:  rgba(32, 32, 32, 0.904);\r\n"
        			+ "    margin-left: 1230px;\r\n"
        			+ "    margin-top: -480px;\r\n"
        			+ "}\r\n"
        			+ ".rightbottom{\r\n"
        			+ "    height: 80px;\r\n"
        			+ "    width: 180px;\r\n"
        			+ "    box-shadow: 9px 12px 5px rgba(0, 0, 0, 0.74) ;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "    background-color: rgb(25, 25, 25);\r\n"
        			+ "    margin-left: 1240px;\r\n"
        			+ "    margin-top: 35px;\r\n"
        			+ "}\r\n"
        			+ ".rightbottom:hover{\r\n"
        			+ "    height: 80px;\r\n"
        			+ "    transition: 0.5s;\r\n"
        			+ "    width: 180px;\r\n"
        			+ "    box-shadow: 9px 12px 5px rgba(0, 0, 0, 0.74) ;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "    background-color:  rgba(8, 95, 1, 0.904);\r\n"
        			+ "    margin-left: 1240px;\r\n"
        			+ "    margin-top: 35px;\r\n"
        			+ "}\r\n"
        			+ ".updatep{\r\n"
        			+ "    height: 65px;\r\n"
        			+ "    width: 130px;\r\n"
        			+ "    font-size: 19px;\r\n"
        			+ "    padding-left: 50px;\r\n"
        			+ "    padding-top: 18px;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "}\r\n"
        			+ ".updatep a{\r\n"
        			+ "    text-decoration: none;\r\n"
        			+ "    font-family: Arial, Helvetica, sans-serif;\r\n"
        			+ "    color: rgb(153, 150, 150);\r\n"
        			+ "}\r\n"
        			+ ".updatep a:hover{\r\n"
        			+ "    text-decoration: none;\r\n"
        			+ "    font-family: Arial, Helvetica, sans-serif;\r\n"
        			+ "    color: rgb(0, 0, 0);\r\n"
        			+ "}\r\n"
        			+ "\r\n"
        			+ ".updatep:hover{\r\n"
        			+ "    height: 65px;\r\n"
        			+ "    width: 130px;\r\n"
        			+ "    font-size: 20px;\r\n"
        			+ "    padding-left: 50px;\r\n"
        			+ "    padding-top: 18px;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ " \r\n"
        			+ "}\r\n"
        			+ ".rightbottom2{\r\n"
        			+ "    height: 80px;\r\n"
        			+ "    width: 150px;\r\n"
        			+ "    box-shadow: 9px 12px 5px rgba(0, 0, 0, 0.74) ;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "    background-color:  rgb(25, 25, 25);\r\n"
        			+ "    margin-left: 1440px;\r\n"
        			+ "    margin-top: -80px;\r\n"
        			+ "}\r\n"
        			+ ".rightbottom2:hover{\r\n"
        			+ "    height: 80px;\r\n"
        			+ "    width: 150px;\r\n"
        			+ "    box-shadow: 9px 12px 5px rgba(0, 0, 0, 0.74) ;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "    background-color:  rgba(141, 0, 0, 0.904);\r\n"
        			+ "    margin-left: 1440px;\r\n"
        			+ "    margin-top: -80px;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "   \r\n"
        			+ "}\r\n"
        			+ ".logout{\r\n"
        			+ "    color:   rgba(189, 5, 5, 0.904);\r\n"
        			+ "    font-family: Arial, Helvetica, sans-serif;\r\n"
        			+ "    font-size: 25px;\r\n"
        			+ "    height: 53px;\r\n"
        			+ "    width: 130px;\r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "    padding-left: 20px;\r\n"
        			+ "    padding-top: 25px;\r\n"
        			+ "    transition: 0.5s;\r\n"
        			+ "}\r\n"
        			+ ".logout:hover{\r\n"
        			+ "    color:   rgba(255, 255, 255, 0.904);\r\n"
        			+ "    font-family: Arial, Helvetica, sans-serif;\r\n"
        			+ "    font-size: 24px;\r\n"
        			+ "    height: 53px;\r\n"
        			+ "    width: 130px;\r\n"
        			+ "   \r\n"
        			+ "    border-radius: 10px;\r\n"
        			+ "    padding-left: 21px;\r\n"
        			+ "    padding-top: 26px;\r\n"
        			+ "}\r\n"
        			+ ".details11{\r\n"
        			+ " color: transparent;\r\n"
        			+ " font-size: 2px;\r\n"
        			+ "}\r\n"
        			+ ".details1{\r\n"
        			+ "    font-size: 26px;\r\n"
        			+ "  \r\n"
        			+ "    margin-top: 35px;\r\n"
        			+ "    color:   rgba(173, 169, 169, 0.904);\r\n"
        			+ "    font-family: Arial, Helvetica, sans-serif;\r\n"
        			+ "}\r\n"
        			+ ".detailsall{\r\n"
        			+ "    width: 300px;\r\n"
        			+ "    margin-left: 65px;\r\n"
        			+ "}\r\n"
        			+ ".detailsip{\r\n"
        			+ "    width: 200px;\r\n"
        			+ "    margin-left: 300px;\r\n"
        			+ "    margin-top: -463px;\r\n"
        			+ "}\r\n"
        			+ ".details{\r\n"
        			+ "    width: 370px;\r\n"
        			+ "    height: 30px;\r\n"
        			+ "    font-size: 27px;\r\n"
        			+ "    border: transparent;\r\n"
        			+ "    outline: 0;\r\n"
        			+ "    background-color: transparent;\r\n"
        			+ "    color: rgb(174, 179, 179);\r\n"
        			+ "}\r\n"
        			+ ".abform{\r\n"
        			+ "    margin-left: 20px;\r\n"
        			+ "    padding-top: 50px;\r\n"
        			+ "    padding-bottom: 60px;\r\n"
        			+ "    color:   rgba(175, 175, 177, 0.664);;\r\n"
        			+ "    font-family: Arial, Helvetica, sans-serif;\r\n"
        			+ "    padding-left: 20px;\r\n"
        			+ "    font-size: 17px;\r\n"
        			+ "}\r\n"
        			+ ".delete{\r\n"
        			+ "    border: 1px solid white;\r\n"
        			+ "    background-color: transparent;\r\n"
        			+ "    width: 170px;\r\n"
        			+ "    height: 40px;\r\n"
        			+ "    margin-left: 80px;\r\n"
        			+ "    margin-top: 320px;\r\n"
        			+ "}\r\n"
        			+ ".delete:hover{\r\n"
        			+ "    border: 1px solid rgb(255, 1, 1);\r\n"
        			+ "    background-color: transparent;\r\n"
        			+ "    width: 170px;\r\n"
        			+ "    height: 40px;\r\n"
        			+ "    margin-left: 80px;\r\n"
        			+ "    margin-top: 320px;\r\n"
        			+ "    \r\n"
        			+ "}\r\n"
        			+ ".delete a{\r\n"
        			+ "   \r\n"
        			+ "    text-decoration: none;\r\n"
        			+ "    color: rgb(168, 166, 166);\r\n"
        			+ "}\r\n"
        			+ ".delete a:hover{\r\n"
        			+ "   \r\n"
        			+ "    text-decoration: none;\r\n"
        			+ "    color: rgb(252, 8, 0);\r\n"
        			+ "}\r\n"
        			+ ".mgif{\r\n"
        			+ "    height: 350px;\r\n"
        			+ "    width: 365px;\r\n"
        			+ "    \r\n"
        			+ "    \r\n"
        			+ "    border-radius: 5px;\r\n"
        			+ "    opacity: 0.3;\r\n"
        			+ "}\r\n"
        			+ "\r\n"
        			+ "    </style>\r\n"
        			+ "</head>\r\n"
        			+ "<body>\r\n"
        			+ " <form  action=\"teacherdashboard\" method=\"get\">\r\n"
        			+ "    <div class=\"frame\">\r\n"
        			+ "       \r\n"
        			+ "        <div class=\"leftframe\">\r\n"
        			+ "            <div class=\"abform\">\r\n"
        			+ "            \r\n"
        			+ "                <h1>DASH-BOARD</h1>\r\n"
        			+ "                \r\n"
        			+ "            </div>\r\n"
        			+ "                <div class=\"profile1\">\r\n"
        			+ "                    <h1 class=\"a\"><i class=\"fa-solid fa-user fa-lg\" style=\"color: #02a8a0;\"></i>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"\">PROFILE</a></h1>\r\n"
        			+ "                </div>\r\n"
        			+ "                <div class=\"profile\">\r\n"
        			+ "                    <h1 class=\"a\"><i class=\"fa-solid fa-circle-info fa-lg\" style=\"color: #8f8c8c;\"></i>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"dbtdetails.html\">DETAILS</a></h1>\r\n"
        			+ "                </div>\r\n"
        			+ "                <div class=\"profile\">\r\n"
        			+ "                    <h1 class=\"a\"><i class=\"fa-solid fa-user-graduate fa-lg\" style=\"color:  #8f8c8c;\"></i>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"dbtstu.html\">STUDENTS</a></h1>\r\n"
        			+ "                </div>\r\n"
        			+ "                <div class=\"profile\">\r\n"
        			+ "                    <h1 class=\"a\"><i class=\"fa-solid fa-book fa-lg\" style=\"color:  #8f8c8c;\"></i>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"dbtmotes.html\">NOTES</a></h1>\r\n"
        			+ "                </div>\r\n"
        			+ "                <button class=\"delete\"><a href=\"\">DELETE PROFILE</a></button>\r\n"
        			+ "        </div>\r\n"
        			+ "        <div class=\"topright\">\r\n"
        			+ "            <img class=\"book\" src=\"images/AEyH.gif\" alt=\"\">\r\n"
        			+ "            <h1 class=\"mitheading\">M . I . T <br> UNIVERSITY </h1>\r\n"
        			+ "            <h1 class=\"dash\">TEACHERS'S  &nbsp;Dash-Board</h1>\r\n"
        			+ "            <h1 class=\"welcome\">WELCOME</h1>\r\n"
        			+ "            <input class=\"name2\" type=\"text\"dir=\"rtl\" value='"+rs.getString("firstname")+" "+rs.getString("lastname")+"'>\r\n"
        			+ "            \r\n"
        			+ "           \r\n"
        			+ "        </div>\r\n"
        			+ "        \r\n"
        			+ "        <div class=\"leftbottom\">\r\n"
        			+ "            <div class=\"detailsall\">\r\n"
        			+ "                <h4 class=\"details11\"> NAME : </h4>\r\n"
        			+ "                \r\n"
        			+ "                <h4 class=\"details1\">FIRST NAME :  </h4>\r\n"
        			+ "               \r\n"
        			+ "                <h4 class=\"details1\">LAST NAME : </h4>\r\n"
        			+ "\r\n"
        			+ "                <h4 class=\"details1\">USERNAME : </h4>\r\n"
        			+ "              \r\n"
        			+ "                <h4 class=\"details1\">EMAIL : </h4>\r\n"
        			+ "             \r\n"
        			+ "                <h4 class=\"details1\">PHONE : </h4>\r\n"
        			+ "                \r\n"
        			+ "                <h4 class=\"details1\">DEPARTMENT : </h4>\r\n"
        			+ "               \r\n"
        			+ "                <h4 class=\"details1\">EMPLOYER ID: </h4>\r\n"
        			+ "               \r\n"
        			+ "            </div>\r\n"
        			+ "            <div class=\"detailsip\">\r\n"
        			+ "               \r\n"
        			+ "                <h4 class=\"details1\"><input type=\"text\" class=\"details\" value='"+rs.getString("firstname")+"'></h4>\r\n"
        			+ "               \r\n"
        			+ "                <h4 class=\"details1\"><input type=\"text\" class=\"details\" value='"+rs.getString("lastname")+"'></h4>\r\n"
        			+ "\r\n"
        			+ "                <h4 class=\"details1\"><input type=\"text\" class=\"details\" value='"+rs.getString("username")+"'></h4>\r\n"
        			+ "              \r\n"
        			+ "                <h4 class=\"details1\"><input type=\"text\" class=\"details\" value='"+rs.getString("email")+"'></h4>\r\n"
        			+ "             \r\n"
        			+ "                <h4 class=\"details1\"><input type=\"text\" class=\"details\" value='"+rs.getString("phone")+"'></h4>\r\n"
        			+ "                \r\n"
        			+ "                <h4 class=\"details1\"><input type=\"text\" class=\"details\" value='"+rs.getString("branch")+"'></h4>\r\n"
        			+ "               \r\n"
        			+ "                <h4 class=\"details1\"><input type=\"text\" class=\"details\" value='"+rs.getString("empid")+"'> </h4>\r\n"
        			+ "               \r\n"
        			+ "            </div>\r\n"
        			+ "        </div>\r\n"
        			+ "        <div class=\"rightmiddle\">\r\n"
        			+ "             <img  class=\"mgif\" src=\"images/minimalist.gif\" alt=\"\">\r\n"
        			+ "        </div>\r\n"
        			+ "        <div class=\"rightbottom\">\r\n"
        			+ "            <h1 class=\"updatep\"><a href=\"updatep.html\">UPDATE PROFILE</a></h1>\r\n"
        			+ "        </div>\r\n"
        			+ "        <div class=\"rightbottom2\">\r\n"
        			+ "            <h1 class=\"logout\">LOGOUT</h1>\r\n"
        			+ "        </div>\r\n"
        			+ "       \r\n"
        			+ "    </div>\r\n"
        			+ "</form>\r\n"
        			+ "</body>\r\n"
        			+ "</html>");
        	}
		} catch (Exception e) {
			// TODO: handle exception
		}
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		System.out.println("GETa");
		
	}

}
